name: Build

on:
  pull_request:

jobs:
  evaluate:
    name: List packages
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v19

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List packages
        id: list-packages
        run: |
          nix flake show --allow-import-from-derivation --json | jq -rc 'to_entries | map( .key as $section | select($section == "checks" or $section == "packages") | .value."x86_64-linux" | keys | map({ name: ., path: "\($section).x86_64-linux.\(.)" }) ) | flatten | "packages=\(.)"' >> $GITHUB_OUTPUT

    outputs:
      packages: ${{ steps.list-packages.outputs.packages }}

  build:
    needs: evaluate
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build: ${{ fromJSON(needs.evaluate.outputs.packages) }}

    name: Build ${{ matrix.build.name }}

    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v19

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build ${{ matrix.build.name }}
        run: nix -L build .#${{ matrix.build.path }}
